compiladores/apps/PerfilUsuario/urls.py
from apps.PerfilUsuario.views import RegisterView, crear_perfil
from django.urls import path

urlpatterns = [
    path('crearPerfil', crear_perfil, name='crearPerfil'),
]

compiladores/compiladores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.Usuario.urls')),
    path('Perfil/', include('apps.PerfilUsuario.urls')),
    path('Codigo/', include('apps.codigo.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    path('reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'},
         name='password_reset_confirm'),
    path('reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'},
         name='password_reset_complete'),
]

compiladores/apps/PerfilUsuario/models.py
from django.db import models
from apps.pais.models import Pais
from apps.lenguaje.models import Lenguaje

# Create your models here.

class PerfilUsuario(models.Model):

    username = models.CharField(max_length=35)
    nombre1 = models.CharField(max_length=35)
    nombre2 = models.CharField(max_length=35)
    apellido1 = models.CharField(max_length=35)
    apellido2 = models.CharField(max_length=35)
    edad = models.CharField(max_length=4)
    ciudad = models.CharField(max_length=35)
    telefono = models.CharField(max_length=35)
    pais = models.ForeignKey(Pais, null=True, blank=True, on_delete=models.CASCADE)
    lenguaje = models.ForeignKey(Lenguaje, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username.__str__()

compiladores/apps/PerfilUsuario/forms.py
from django import forms
from apps.PerfilUsuario.models import PerfilUsuario

class PerfilForm(forms.ModelForm):

    class Meta:
        model = PerfilUsuario

        fields = [
            'username',
            'nombre1',
            'nombre2',
            'apellido1',
            'apellido2',
            'edad',
            'ciudad',
            'telefono',
            'pais',
            'lenguaje',
        ]

        labels = {
            'username':'Nombre de usuario',
            'nombre1': 'Primer Nombre',
            'nombre2': 'Segundo Nombre',
            'apellido1': 'Primer Apelido',
            'apellido2': 'Segundo Apellido',
            'edad': 'Edad',
            'ciudad': 'Ciudad',
            'telefono': 'Telefono',
            'pais':'Pais',
            'lenguaje':'Lenguaje',
        }

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'nombre1': forms.TextInput(attrs={'class':'form-control'}),
            'nombre2': forms.TextInput(attrs={'class':'form-control'}),
            'apellido1': forms.TextInput(attrs={'class':'form-control'}),
            'apellido2': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'pais': forms.Select(attrs={'class': 'form-control'}),
            'lenguaje': forms.Select(attrs={'class': 'form-control'}),
        }


class CreateForm(forms.ModelForm):

    #'nombre1', 'nombre2', 'apellido1', 'apellido2', 'edad', 'ciudad', 'telefono','pais', 'lenguaje',

    class Meta:
        model = PerfilUsuario
        fields = ( 'nombre1','nombre2', 'apellido1', 'apellido2', 'edad', 'ciudad', 'telefono','pais', 'lenguaje')

compiladores/apps/PerfilUsuario/views.py
from apps.PerfilUsuario.forms import CreateForm
from django.views.generic import CreateView
from django.shortcuts import redirect, render
from apps.PerfilUsuario.forms import PerfilForm
from apps.Usuario.models import Usuario
from apps.PerfilUsuario.models import PerfilUsuario

# Create your views here.

class RegisterView(CreateView):
    form_class = CreateForm
    template_name = 'PerfilUsuario/crearPerfil.html'
    success_url = '../principal'

def crear_perfil(request):

    if request.method == 'POST':
        form = PerfilForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            print("Username: ", username)

            try:
                usuario_buscado = Usuario.objects.get(username=username)

                print("Buscando usuario")

                if usuario_buscado.perfil == None:

                    form.save()

                    try:
                        print("Buscando perfil")

                        perfil_buscado = PerfilUsuario.objects.get(username=username)
                        usuario_buscado.perfil = perfil_buscado
                        usuario_buscado.save()

                    except PerfilUsuario.DoesNotExist:
                        print("Perfil no encontrado")

            except Usuario.DoesNotExist:
                print("No se pudo crear el usuario")


        return redirect('principal')

    else:
        form = PerfilForm()

        return render(request, 'PerfilUsuario/crearPerfil.html', {'form': form})

compiladores/templates/PerfilUsuario/crearPerfil.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
Crear Perfil
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}

<div class="jumbotron">
    <h2 class="display-3">Crear perfil</h2>

    <form action="" method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <p><label for="{{ form.username.id_for_label }}">Nombre de usuario:</label>
        <input type="text" id="{{ form.username.id_for_label }}" name="username" maxlength="35" value="{{user.username}}" required></p>

        <p><label for="id_nombre1">Primer nombre:</label>
        {{ form.nombre1 }}</p>

        <p><label for="id_nombre2">Segundo nombre:</label>
        {{ form.nombre2 }}</p>

        <p><label for="id_apellido1">Primer apellido:</label>
        {{ form.apellido1 }}</p>

        <p><label for="id_apellido2">Segundo apellido:</label>
        {{ form.apellido2 }}</p>

        <p><label for="id_edad">Edad:</label>
        {{ form.edad }}</p>

        <p><label for="id_ciudad">Ciudad:</label>
        {{ form.ciudad }}</p>

        <p><label for=" {{form.telefono.id_for_label }}">Telefono:</label>
        {{ form.telefono }}</p>

        <p><label for=" {{form.pais.id_for_label }}">Pais:</label>
        {{ form.pais }}</p>

        <p><label for=" {{form.lenguaje.id_for_label }}">Lenguaje:</label>
        {{ form.lenguaje }}</p>

        <button class="btn btn-success" type="submit">
                <i class="fa fa-share-square"></i>&nbsp;Guardar
        </button>
    </form>
</div>
{% endblock %}